//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMAFACTURACIONV1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pagos()
        {
            this.DetalleMediosPagos = new HashSet<DetalleMediosPagos>();
            this.DetallesPago = new HashSet<DetallesPago>();
        }
    
        public int Idpago { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> idMedioPago { get; set; }
        public Nullable<int> idCuentaCorriente { get; set; }
        public string Nocheque { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<double> Importe { get; set; }
        public string Concepto { get; set; }
    
        public virtual Bancos Bancos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleMediosPagos> DetalleMediosPagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesPago> DetallesPago { get; set; }
        public virtual MediosPago MediosPago { get; set; }
    }
}
