//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMAFACTURACIONV1._0.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_Almacen> Table_Almacen { get; set; }
        public virtual DbSet<Table_Articulos> Table_Articulos { get; set; }
        public virtual DbSet<Table_Banco> Table_Banco { get; set; }
        public virtual DbSet<Table_Categoria> Table_Categoria { get; set; }
        public virtual DbSet<Table_CentroCosto> Table_CentroCosto { get; set; }
        public virtual DbSet<Table_Comprobante> Table_Comprobante { get; set; }
        public virtual DbSet<Table_CondicionCompra> Table_CondicionCompra { get; set; }
        public virtual DbSet<Table_Contable> Table_Contable { get; set; }
        public virtual DbSet<Table_CuentaCorriente> Table_CuentaCorriente { get; set; }
        public virtual DbSet<Table_DetalleMediosPago> Table_DetalleMediosPago { get; set; }
        public virtual DbSet<Table_DetallePago> Table_DetallePago { get; set; }
        public virtual DbSet<Table_Empleado> Table_Empleado { get; set; }
        public virtual DbSet<Table_Empresa> Table_Empresa { get; set; }
        public virtual DbSet<Table_Estados> Table_Estados { get; set; }
        public virtual DbSet<Table_Localidades> Table_Localidades { get; set; }
        public virtual DbSet<Table_MedioPago> Table_MedioPago { get; set; }
        public virtual DbSet<Table_Pagos> Table_Pagos { get; set; }
        public virtual DbSet<Table_Profiles> Table_Profiles { get; set; }
        public virtual DbSet<Table_Proveedores> Table_Proveedores { get; set; }
        public virtual DbSet<Table_Provincias> Table_Provincias { get; set; }
        public virtual DbSet<Table_TipoComprobante> Table_TipoComprobante { get; set; }
        public virtual DbSet<Table_TipoFactura> Table_TipoFactura { get; set; }
        public virtual DbSet<Table_Ubicacion> Table_Ubicacion { get; set; }
        public virtual DbSet<Table_User> Table_User { get; set; }
        public virtual DbSet<Table_Vencimiento> Table_Vencimiento { get; set; }
        public virtual DbSet<Table_Zonas> Table_Zonas { get; set; }
        public virtual DbSet<View_Almacenes> View_Almacenes { get; set; }
        public virtual DbSet<View_DetalleArticulo> View_DetalleArticulo { get; set; }
        public virtual DbSet<View_DetalleArticuloComprobante> View_DetalleArticuloComprobante { get; set; }
        public virtual DbSet<View_DETALLEFACTURA> View_DETALLEFACTURA { get; set; }
        public virtual DbSet<View_ListaEmpleados> View_ListaEmpleados { get; set; }
        public virtual DbSet<View_OrdenPago> View_OrdenPago { get; set; }
        public virtual DbSet<View_Proveedores> View_Proveedores { get; set; }
        public virtual DbSet<Table_IngresoMateriales> Table_IngresoMateriales { get; set; }
        public virtual DbSet<Table_DetallesComprobanteArticulos> Table_DetallesComprobanteArticulos { get; set; }
    
        public virtual ObjectResult<EncabezadoDeuda_Result> EncabezadoDeuda(Nullable<int> idproveedor)
        {
            var idproveedorParameter = idproveedor.HasValue ?
                new ObjectParameter("idproveedor", idproveedor) :
                new ObjectParameter("idproveedor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EncabezadoDeuda_Result>("EncabezadoDeuda", idproveedorParameter);
        }
    
        public virtual ObjectResult<EncabezadoOrdenPago_Result> EncabezadoOrdenPago(Nullable<int> idPago)
        {
            var idPagoParameter = idPago.HasValue ?
                new ObjectParameter("IdPago", idPago) :
                new ObjectParameter("IdPago", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EncabezadoOrdenPago_Result>("EncabezadoOrdenPago", idPagoParameter);
        }
    
        public virtual ObjectResult<FacturasPendientesPago_Result> FacturasPendientesPago(Nullable<int> idproveedor)
        {
            var idproveedorParameter = idproveedor.HasValue ?
                new ObjectParameter("idproveedor", idproveedor) :
                new ObjectParameter("idproveedor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FacturasPendientesPago_Result>("FacturasPendientesPago", idproveedorParameter);
        }
    
        public virtual ObjectResult<OrdenPago_Result> OrdenPago(Nullable<int> idpago)
        {
            var idpagoParameter = idpago.HasValue ?
                new ObjectParameter("Idpago", idpago) :
                new ObjectParameter("Idpago", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrdenPago_Result>("OrdenPago", idpagoParameter);
        }
    
        public virtual ObjectResult<SeleccionarMediosDePagos_Result> SeleccionarMediosDePagos(Nullable<int> idPago)
        {
            var idPagoParameter = idPago.HasValue ?
                new ObjectParameter("idPago", idPago) :
                new ObjectParameter("idPago", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SeleccionarMediosDePagos_Result>("SeleccionarMediosDePagos", idPagoParameter);
        }
    
        public virtual ObjectResult<FACTURASXPROVEEDORES_Result> FACTURASXPROVEEDORES(Nullable<System.DateTime> fECHAINICIO, Nullable<System.DateTime> fECHAFIN, Nullable<int> iDPROVEEDOR)
        {
            var fECHAINICIOParameter = fECHAINICIO.HasValue ?
                new ObjectParameter("FECHAINICIO", fECHAINICIO) :
                new ObjectParameter("FECHAINICIO", typeof(System.DateTime));
    
            var fECHAFINParameter = fECHAFIN.HasValue ?
                new ObjectParameter("FECHAFIN", fECHAFIN) :
                new ObjectParameter("FECHAFIN", typeof(System.DateTime));
    
            var iDPROVEEDORParameter = iDPROVEEDOR.HasValue ?
                new ObjectParameter("IDPROVEEDOR", iDPROVEEDOR) :
                new ObjectParameter("IDPROVEEDOR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FACTURASXPROVEEDORES_Result>("FACTURASXPROVEEDORES", fECHAINICIOParameter, fECHAFINParameter, iDPROVEEDORParameter);
        }
    }
}
