//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMAFACTURACIONV1._0.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Banco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Banco()
        {
            this.Table_DetalleMediosPago = new HashSet<Table_DetalleMediosPago>();
            this.Table_Pagos = new HashSet<Table_Pagos>();
        }
    
        public int IdBanco { get; set; }
        public string Nombre { get; set; }
        public string Sucursal { get; set; }
        public string TipoCuenta { get; set; }
        public string Numero { get; set; }
        public string CBU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_DetalleMediosPago> Table_DetalleMediosPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Pagos> Table_Pagos { get; set; }
    }
}
