//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMAFACTURACIONV1._0.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Empleado()
        {
            this.Table_Almacen = new HashSet<Table_Almacen>();
            this.Table_IngresoMateriales = new HashSet<Table_IngresoMateriales>();
        }
    
        public int IDEmpleado { get; set; }
        public string Apellidos { get; set; }
        public string Nombre { get; set; }
        public string cuit { get; set; }
        public string cuil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Almacen> Table_Almacen { get; set; }
        public virtual Table_Empleado Table_Empleado1 { get; set; }
        public virtual Table_Empleado Table_Empleado2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_IngresoMateriales> Table_IngresoMateriales { get; set; }
    }
}
