//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMAFACTURACIONV1._0.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Articulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Articulos()
        {
            this.Table_IngresoMateriales = new HashSet<Table_IngresoMateriales>();
            this.Table_DetallesComprobanteArticulos = new HashSet<Table_DetallesComprobanteArticulos>();
        }
    
        public int IDArticulo { get; set; }
        public int IDCategoria { get; set; }
        public Nullable<int> IdAlmacen { get; set; }
        public Nullable<int> IdUbicacion { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Codigo { get; set; }
        public Nullable<double> Stock { get; set; }
        public Nullable<double> Iva { get; set; }
    
        public virtual Table_Categoria Table_Categoria { get; set; }
        public virtual Table_Ubicacion Table_Ubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_IngresoMateriales> Table_IngresoMateriales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_DetallesComprobanteArticulos> Table_DetallesComprobanteArticulos { get; set; }
    }
}
