//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMAFACTURACIONV1._0.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Proveedores()
        {
            this.Table_Comprobante = new HashSet<Table_Comprobante>();
        }
    
        public int IdProveedores { get; set; }
        public string Nombre { get; set; }
        public string Razon { get; set; }
        public string Cuit { get; set; }
        public string IngresosBrutos { get; set; }
        public string Direccion { get; set; }
        public string IDProvincia { get; set; }
        public string IDLocalidad { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Comprobante> Table_Comprobante { get; set; }
        public virtual Table_Localidades Table_Localidades { get; set; }
        public virtual Table_Provincias Table_Provincias { get; set; }
    }
}
