//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMAFACTURACIONV1._0.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Comprobante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Comprobante()
        {
            this.Table_DetallePago = new HashSet<Table_DetallePago>();
            this.Table_DetallesComprobanteArticulos = new HashSet<Table_DetallesComprobanteArticulos>();
        }
    
        public int IdComprobante { get; set; }
        public string Sucursal { get; set; }
        public string NoFactura { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<int> IdTipoComprobante { get; set; }
        public Nullable<int> IdCentroCosto { get; set; }
        public Nullable<int> IdTipoFactura { get; set; }
        public Nullable<double> Importe { get; set; }
        public Nullable<int> Contable { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdCondicionCompra { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<double> IIBB { get; set; }
        public Nullable<double> Retenciones { get; set; }
        public Nullable<double> ConceptosNograbado { get; set; }
    
        public virtual Table_CentroCosto Table_CentroCosto { get; set; }
        public virtual Table_CondicionCompra Table_CondicionCompra { get; set; }
        public virtual Table_Contable Table_Contable { get; set; }
        public virtual Table_Estados Table_Estados { get; set; }
        public virtual Table_Proveedores Table_Proveedores { get; set; }
        public virtual Table_TipoComprobante Table_TipoComprobante { get; set; }
        public virtual Table_TipoFactura Table_TipoFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_DetallePago> Table_DetallePago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_DetallesComprobanteArticulos> Table_DetallesComprobanteArticulos { get; set; }
    }
}
