//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMAFACTURACIONV1._0.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Pagos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Pagos()
        {
            this.Table_DetalleMediosPago = new HashSet<Table_DetalleMediosPago>();
            this.Table_DetallePago = new HashSet<Table_DetallePago>();
        }
    
        public int Idpago { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> idMedioPago { get; set; }
        public Nullable<int> idCuentaCorriente { get; set; }
        public string Nocheque { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<double> Importe { get; set; }
        public string Concepto { get; set; }
    
        public virtual Table_Banco Table_Banco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_DetalleMediosPago> Table_DetalleMediosPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_DetallePago> Table_DetallePago { get; set; }
        public virtual Table_MedioPago Table_MedioPago { get; set; }
    }
}
