//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMAFACTURACIONV1._0.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_OrdenPago
    {
        public int Idpago { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string MediosPago { get; set; }
        public string Nocheque { get; set; }
        public string Banco { get; set; }
        public Nullable<double> Importe { get; set; }
        public string Concepto { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public string TipoFactura { get; set; }
        public string Sucursal { get; set; }
        public string NoFactura { get; set; }
        public Nullable<double> ImporteFactura { get; set; }
        public string RazonProveedor { get; set; }
    }
}
