//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMAFACTURACIONV1._0.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Almacenes
    {
        public int IdAlmacen { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public string NombreEncargado { get; set; }
        public string Zonas { get; set; }
    }
}
