//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMAFACTURACIONV1._0.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DETALLEFACTURA
    {
        public int IdComprobante { get; set; }
        public string TipoComprobante { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string TipoFactura { get; set; }
        public string Sucursal { get; set; }
        public string NoFactura { get; set; }
    }
}
